[package]
name = "innen-core"
version = "0.4.0"
license = "MIT"
edition = "2021"
rust-version = "1.90"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
fs2 = { workspace = true }
tantivy = { workspace = true }
redb = { workspace = true }
jieba-rs = { workspace = true }
tiktoken-rs = { workspace = true }
yaml-rust2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
